# Generated by Django 5.1.11 on 2025-08-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_placeimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placeimage',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='placeimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
