# Generated by Django 5.1.11 on 2025-08-26 13:30

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_rename_description_long_place_long_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='short_description',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Краткое описание'),
        ),
    ]
