# Generated by Django 5.1.11 on 2025-08-27 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_alter_place_long_description'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='placeimage',
            index=models.Index(fields=['place', 'order'], name='place_order_idx'),
        ),
    ]
