# Generated by Django 5.1.11 on 2025-08-29 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_alter_place_title_alter_placeimage_order_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='placeimage',
            name='place_order_idx',
        ),
        migrations.AddIndex(
            model_name='placeimage',
            index=models.Index(fields=['order'], name='order_idx'),
        ),
    ]
