# Generated by Django 5.1.11 on 2025-08-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_remove_placeimage_place_order_idx_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='place',
            constraint=models.UniqueConstraint(fields=('title', 'lng', 'lat'), name='unique_place_coords_title'),
        ),
    ]
